environment = ["MY_ENV", "NODE_ENV"]

[cache]
directory = "./node_modules/.cache/"
max_age = 3600
stale_while_revalidate = 3600

[environments]
[environments.development]
alias = ["dev"]
project = "p1"

[environments.production]
alias = ["prod"]
project = "p2"
cache_dir = "./node_modules/.cache/prod"
