environment = ["MY_ENV", "NODE_ENV"]

[cache]
directory = "./node_modules/.cache/"
max_age = 3600
stale_while_revalidate = 3600

[profiles]
[profiles.development]
alias = ["dev"]
project = "p1"

[profiles.production]
alias = ["prod"]
project = "p2"
cache_dir = "./node_modules/.cache/prod"
