[package]
name = "bwenv"
version = "0.1.1"
edition = "2021"

[dependencies]
bitwarden = { version = "0.3.0", features = ["secrets"] }
clap = { version = "4.4.2", features = ["derive", "cargo", "env"] }
clap-markdown = "0.1.3"
log = "0.4.20"
serde = "1.0.188"
simple_logger = { version = "4.2.0", default-features = false, features = [
	"colors",
] }
tokio = { version = "1.32.0", features = ["full"] }
toml = "0.7.6"
uuid = "1.4.1"
