on:
  push:
    branches:
      - master
  pull_request:

name: CI

env:
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:
  # check:
  #   name: Check, Format, Lint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: mozilla-actions/sccache-action@v0.0.3
  #     - uses: actions-rs/toolchain@v1
  #       with:
  #         profile: minimal
  #         toolchain: stable
  #         override: true
  #
  #     - name: Check
  #       uses: actions-rs/cargo@v1
  #       with:
  #         command: check
  #
  #     - name: Format
  #       uses: actions-rs/cargo@v1
  #       with:
  #         command: fmt
  #         args: --all -- --check
  #
  #     - name: Lint
  #       uses: actions-rs/cargo@v1
  #       with:
  #         command: clippy
  #         args: -- -D warnings

  build-linux:
    name: Build for x86_64-unknown-linux-gnu
    # needs: check
    # if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mozilla-actions/sccache-action@v0.0.3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: x86_64-unknown-linux-gnu

      - name: Build for x86_64-unknown-linux-gnu
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target x86_64-unknown-linux-gnu

      - name: Store build artifact
        uses: actions/upload-artifact@v3
        with:
          name: x86_64-unknown-linux-gnu
          path: ./target/x86_64-unknown-linux-gnu/release/bwenv

  build-apple-silicon:
    name: Build aarch64-apple-darwin
    # needs: check
    # if: github.ref == 'refs/heads/master'
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mozilla-actions/sccache-action@v0.0.3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: aarch64-apple-darwin

      - name: Build for aarch64-apple-darwin
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target aarch64-apple-darwin

      - name: Store build artifact
        uses: actions/upload-artifact@v3
        with:
          name: aarch64-apple-darwin
          path: ./target/aarch64-apple-darwin/release/bwenv

  release:
    name: Release
    needs:
      - build-linux
      - build-apple-silicon
    # if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download build artifacts for x86_64-unknown-linux-gnu
        uses: actions/download-artifact@v2
        with:
          name: x86_64-unknown-linux-gnu
          path: .

      - name: Download build artifacts for aarch64-apple-darwin
        uses: actions/download-artifact@v2
        with:
          name: aarch64-apple-darwin
          path: .

      - name: Read version from Cargo.toml
        id: get_version
        run: echo "::set-output name=version$(awk -F' = ' '/^version/ {gsub(/"/, "", $2); print $2}' Cargo.toml)"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./target/x86_64-unknown-linux-gnu/release/bwenv
            ./target/aarch64-apple-darwin/release/bwenv
          tag_name: "v${{ steps.get_version.outputs.version }}"
          release_name: "Release v${{ steps.get_version.outputs.version }}"
